name: "Changeset Release"
description: "A Github action for creating non-public releases with changesets"

branding:
  icon: octagon
  color: yellow

inputs:
  format:
    description: "The release tag format"
    required: false
  target:
    description: "Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch."
    required: false

outputs:
  tag:
    description: "The release tag"

runs:
  using: "node20"
  main: "dist/index.js"
