name: "Set Commit Status"
description: "A Github action for set github commit status"

branding:
  icon: octagon
  color: yellow

inputs:
  status:
    description: 'The status to be set for commit ("error", "failure", "pending", "success")'
    required: true
  sha:
    description: "Commit hash for which the status is to be set"
    required: true
  context:
    description: "Context of status"
    required: false
  description:
    description: "Description of status"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
