name: Create Release Pull Request

on:
  push:
    branches:
      - main

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    name: Create Release Pull Request

    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup Git user
        run: |
          git config --global user.email "kazuking.1911@gmail.com"
          git config --global user.name "108yen"

      - name: Install dependencies
        run: pnpm install

      - name: Create Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "ci(changesets): update version"
          setupGitUser: false
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
